In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.random.rand(8*8)

array([0.049734  , 0.69729328, 0.25676414, 0.36476293, 0.76855179,
       0.06970712, 0.51579922, 0.48218221, 0.03134146, 0.95862755,
       0.061463  , 0.95694718, 0.09816769, 0.98441544, 0.09248702,
       0.76745553, 0.27983924, 0.91025217, 0.14572118, 0.35191323,
       0.34143979, 0.05307114, 0.27999709, 0.8197488 , 0.09596993,
       0.81635267, 0.15729246, 0.69666025, 0.02999837, 0.48654202,
       0.43604076, 0.51415025, 0.85827544, 0.36507142, 0.95708621,
       0.98993798, 0.12034878, 0.49495181, 0.37958095, 0.014659  ,
       0.08572177, 0.59491855, 0.86782477, 0.75858307, 0.25240368,
       0.44755719, 0.61634557, 0.31004089, 0.16253261, 0.60142181,
       0.06294221, 0.48970905, 0.44114556, 0.04195863, 0.45172045,
       0.87923189, 0.07926862, 0.92396909, 0.71462952, 0.29581073,
       0.07982112, 0.6109239 , 0.6698223 , 0.59403956])

In [6]:
# array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
mat = np.arange(1,26).reshape(5,5)

In [10]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
mat[3:,3:]

array([[19, 20],
       [24, 25]])

In [14]:
mat[2:3,1:2]

array([[12]])

In [15]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [18]:
np.random.rand(10)

array([0.78417618, 0.27018925, 0.30770209, 0.7506922 , 0.7199887 ,
       0.03805528, 0.9894736 , 0.39892723, 0.57128984, 0.58017756])

In [19]:
mat.std()

7.211102550927978

In [21]:
# sum of all rows in the matrix
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [23]:
# sum of all columns in the matrix
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])